### ISSUE TITLE
Attribute searches

### ISSUE THREAD

**Issue by MikeJJohnson** [atomrab/chersark#3]
There are some problems with the faunal species searches, and with clicking through the linked items in the species/anatomical part tables.
The link for the latter looks funny (https://ica.tacc.utexas.edu/chersonesos/ark/search/atr/34/429/1) -- is that a query?
In any case, either clicking that link from a context page or constructing a search by attribute>e.g. "fish">e.g. "raja clavata" returns an endlessly repeating error of the form "the key was FALSE in isItemKey" and then "either the key or value was FALSE in getChLinkUp", and freezes the site.
Presumably these links should either generate a search for all records containing that value, as the other linked attributes in forms do, or link to the concept page. Either one is fine with me -- whichever is going to be more stable as flat HTML.

**Comment by MikeJJohnson** [comment]
Yes the link is a search query in the form https://ica.tacc.utexas.edu/chersonesos/ark/search/{searchkey}/{attrtype}/{attrid}/{boolean}

This should give a list of all the things like that. In this instance there is an error, "the key was FALSE" Which it is as the data is attached to other data, not to key.

Switching these links to be a link to the concept page would be an easy fix to both issues.

**Comment by atomrab** [comment]
Ah, I see. But there are other kinds of data that are attached to other data (like "period") that bring in other results with the same attached data correctly -- why doesn't this work in the same way? In any case, I'm fine having it link to the concept page -- seems like it would probably be more stable for the HTML version. It would, however, be pretty useful to be able to search by species, so that you wouldn't have to go context by context to see where a particular species might appear. Using the faceted attribute search for "fish" throws the same error, regardless of the species you select. Can we fix this? Let's talk about options for preserving search and browse functions when we next meet.

**Comment by MikeJJohnson** [comment]
This has been fixed - It was caused by some orphaned records in the data, which might need more investigation
